CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C
C UMAT FOR ANISOTROPIC ELASTIC VISCOPLASTIC DAMAGE CONSTITUTIVE LAW
C
C CREATED BY JAKOB SCHWIEDRZIK - ISTB - 2012
C
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C
C INCLUDING DENSIFICATION ROUTINE
C
C CREATED BY HADI SEYED HOSSEINI - ILSB - 2011
C
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C
C       MODIFICATIONS 
C
C * ADDED DENSIFICATION ROUTINE - JJS, ISTB, 02/2012   
C     
C * CHANGED TO QUADRIC YIELD SURFACE - JJS, ISTB, 07/2012
C     
C * ADDED PRIMAL CPPA (PEREZ-FOGUET 2002) BASED ON VARIATIONAL 
C   STRUCTURE AS FAIL SAFE FOR NEWTON CPPA TO ENSURE GLOBAL 
C   CONVERGENCE - JJS, ISTB, 08/2012
C
C * ADDED NEW MATERIAL CONSTANTS: ISOTROPIC, TRANSVERSELY ISOTROPIC,
C   FABRIC-BASED ORTHOTROPIC FOR TRABECULAR BONE (PHZ 2013) AND
C   ISOTROPIC AND TRANSVERSELY ISOTROPIC FOR CORTICAL BONE (JJS 2013)                           
C
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C
C  * D E P V A R  
C
C    SDV 1: CUMULATED PLASTIC STRAIN
C    SDV 2: SCALAR DAMAGAE VARIABLE
C    SDV 3-8: PLASTIC STRAIN VECTOR
C    SDV 9-14: NOMINAL STRESS VECTOR
C    SDV 15-20: DENSIFICATION STRESS VECTOR
C    SDV 21: ORIGINAL BVTV
C    SDV 22: UPDATED BVTV 
C
C  * U S E R   M A T E R I A L    
C
C     PROPS(1)  - FLAG FOR PARAMETER SELECTION
C                 0 - TRABECULAR BONE ISOTROPIC
C                 1 - TRABECULAR BONE TRANSVERSELY ISOTROPIC
C                 2 - TRABECULAR BONE FABRIC-BASED ORTHOTROPIC
C                 3 - COMPACT BONE ISOTROPIC
C                 4 - COMPACT BONE TRANSVERSELY ISOTROPIC
C     PROPS(2)  - BV/TV
C     PROPS(3)  - M1
C     PROPS(4)  - M2
C     PROPS(5)  - M3
C     PROPS(6)  - DENSFL
C     PROPS(7)  - VISCFL
C     PROPS(8)  - PYFL
C
C     HARD WIRED FLAGS:
C
C     DENSIFICATOR FLAG: 0 - DENSIFICATION OFF
C                        1 - DENSIFICATION ON
C     VISCOSITY FLAG:    0 - RATE-INDEPENDENT
C                        1 - LINEAR VISCOSITY
C                        2 - EXPONENTIAL VISC
C                        3 - LOGARITHMIC VISC
C                        4 - POLYNOMIAL VISC
C                        5 - POWER LAW VISC 
C     POSTYIELD FLAG:    0 - PERFECT PLASTICITY
C                        1 - EXPONENTIAL HARDENING
C                        2 - SIMPLE SOFTENING
C                        3 - EXPONENTIAL SOFTENING
C                        4 - PIECEWISE SOFTENING
C
C  M E D T O O L  T E M P L A T E 
C     ** XXX to be replaced by user -> Bone flag
C     ** CardName BVTV, EigVal.., replace by medtool 
C     *MATERIAL, NAME=CardName
C     *DEPVAR
C     22
C     *USER MATERIAL, CONSTANTS=5, UNSYMM
C     XXX, BVTV, EigVal3, EigVal2,  EigVal1
CC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC

      SUBROUTINE UMAT(STRESS,STATEV,DDSDDE,SSE,SPD,SCD,RPL,DDSDDT,
     1                DRPLDE,DRPLDT,STRAN,DSTRAN,TIME,DTIME,TEMP,DTEMP,
     2                PREDEF,DPRED,CMNAME,NDI,NSHR,NTENS,NSTATV,PROPS,
     3                NPROPS,COORDS,DROT,PNEWDT,CELENT,DFGRD0,DFGRD1,
     4                NOEL,NPT,LAYER,KSPT,KSTEP,KINC)
C
      IMPLICIT NONE
C
C     INPUT/OUTPUT VARIABLES:
      INTEGER NTENS, NDI, NSHR
      INTEGER NSTATV
      INTEGER NPROPS
C
C     INPUT/OUTPUT VARIABLES THAT HAVE TO BE DEFINED BY THE UMAT
C     IN ALL SITUATIONS:
      DOUBLE PRECISION STRESS(NTENS), STATEV(NSTATV)
      DOUBLE PRECISION DDSDDE(NTENS,NTENS)
      DOUBLE PRECISION SSE,SPD,SCD
C
C     ONLY IN FULLY COUPLED TEMPERATURE-DISPLACEMENT ANALYSIS:
      DOUBLE PRECISION RPL,DDSDDT(NTENS),DRPLDE(NTENS),DRPLDT
C
C     OUTPUT VARIABLES THAT CAN BE UPDATED WITHIN THE UMAT (TIME INC):
      DOUBLE PRECISION PNEWDT
C
C     INPUT VARIABLES: SUPPLIED BY ABAQUS:
      DOUBLE PRECISION STRAN(NTENS), DSTRAN(NTENS)
      DOUBLE PRECISION TIME(2)     , DTIME
      DOUBLE PRECISION TEMP        , DTEMP
      DOUBLE PRECISION PREDEF(1)   , DPRED(1)
      CHARACTER*8      CMNAME
      DOUBLE PRECISION PROPS(NPROPS)
      DOUBLE PRECISION COORDS(3)
      DOUBLE PRECISION DROT(3,3)
      DOUBLE PRECISION CELENT
      DOUBLE PRECISION DFGRD0(3,3) , DFGRD1(3,3)
      INTEGER          NOEL,NPT,LAYER,KSPT,KSTEP,KINC
C
C     EXTERNAL FUNCTIONS
      DOUBLE PRECISION RADK,DRADK,DAM,DDAM,VECNORM 
      DOUBLE PRECISION VISCY,VDYDK,TSFU
C
C     VISCOPLASTIC DAMAGE UMAT VARIABLES
      INTEGER ITER,MAXITER,BF,K1,K2,DENSFL,VISCFL,PYFL
      DOUBLE PRECISION DETF0,MM,ETA,TOL,KONSTD,CRITD
      DOUBLE PRECISION RHO,MM1,MM2,MM3,DELTA
      DOUBLE PRECISION E0,V0,MU0,E33,V30,MU30,KS,LS
      DOUBLE PRECISION SIGD0P,SIGD0N,ZETA0,TAUD0,PP,QQ
      DOUBLE PRECISION SIGD3P,SIGD3N,ZETA30,TAUD30,S0,S3
      DOUBLE PRECISION KSLOPE,KMAX,KWIDTH,RDY
      DOUBLE PRECISION KMIN,GMIN,ND,EXPS
      DOUBLE PRECISION SSSS(NTENS,NTENS),CCCC(NTENS,NTENS)
      DOUBLE PRECISION AAAA(NTENS,NTENS),AA(NTENS)
      DOUBLE PRECISION FFFF(NTENS,NTENS),FF(NTENS)
      DOUBLE PRECISION DDSY(NTENS,NTENS),DSY(NTENS)
      DOUBLE PRECISION ETOT1(NTENS),ETOT0(NTENS),SS0(NTENS)
      DOUBLE PRECISION KAPPA0,DKAPPAI,DKAPPA1,DDK1,KAPPA1
      DOUBLE PRECISION STR(NTENS),SSI(NTENS),SS1(NTENS),DSS1(NTENS)
      DOUBLE PRECISION EPLAS0(NTENS),EPLAS1(NTENS)
      DOUBLE PRECISION YSTR,YS,DYDS(NTENS),DYDK,DMG0
      DOUBLE PRECISION DMG,DDMG,RAD,DRAD,FFS(NTENS),SFFS,SRA(NTENS)
      DOUBLE PRECISION NP(NTENS),DNPDS(NTENS,NTENS),DNPDK(NTENS)
      DOUBLE PRECISION RR(NTENS),DRRDS(NTENS,NTENS),DRRDK(NTENS)
      DOUBLE PRECISION HI,DHDS(NTENS),DHDK,NORMRR,ABSY
      DOUBLE PRECISION SSSA(NTENS,NTENS),TANM(NTENS,NTENS)
C
C     PRIMAL CPP ALGORITHM AND LINE SEARCH VARIABLES
      INTEGER ITERL,FLAG
      DOUBLE PRECISION J11(6,6),J22,J12(6),J21(6)
      DOUBLE PRECISION RRR(7),RRI(7),XXI(7),XX1(7),DDD(7),JJJ(7,7)
      DOUBLE PRECISION INVJ(7,7),DDJ(7,7),AUX,DMK,UPLIM
      DOUBLE PRECISION ETAL,BETA,MKI,MK1,ALPHA1,ALPHA2,ALPHA
C
C     DENSIFICATOR ROUTINE VARIABLES
      DOUBLE PRECISION ECRIT,GAMMAL0,RL,GAMMAP0,RP,POWERDNS
      DOUBLE PRECISION TRACEEN,CRITERION,GAMMAL,GAMMAP
      DOUBLE PRECISION SDNS(6),SDNST(3,3),XIDENV(6),XIDEN(3,3)
      DOUBLE PRECISION XDENSSTIFF1,TANGDENS(6,6)
C
C     Jarunan modified
      DOUBLE PRECISION factor
C 
C     INTERFACE FOR ARRAY VALUED EXTERNAL FUNCTION VECDYAD
      INTERFACE
      FUNCTION VECDYAD(BB,CC)
      DOUBLE PRECISION VECDYAD(6,6)
      DOUBLE PRECISION BB(6),CC(6)
      END FUNCTION VECDYAD
C
C     INTERFACE FOR VECTOR VALUED EXTERNAL FUNCTION VDYDS
      FUNCTION VDYDS(VISCFL,ETA,MM,DTIME,DKAPPA,DHDS,HI)
      DOUBLE PRECISION VDYDS(6)
      DOUBLE PRECISION ETA,MM,DTIME,DKAPPA,DHDS(6),HI
      INTEGER VISCFL
      END FUNCTION VDYDS
      END INTERFACE
C
C     DOT_PRODUCT(VECTOR_A, VECTOR_B) SCALAR PRODUCT
C     MATMUL(MATRIX_A, MATRIX_B) MATRIX MULTIPLICATION
C 
C     TENSOR INITIALISATION
C 
      SSSS=0.0D0
      CCCC=0.0D0
      AAAA=0.0D0
      FFFF=0.0D0
      DDSY=0.0D0
      DNPDS=0.0D0
      DRRDS=0.0D0
      SSSA=0.0D0
      TANM=0.0D0
      JJJ=0.0D0
      INVJ=0.0D0
      DDJ=0.0D0
      J11=0.0D0
C
      DO K1=1,3
        DO K2=1,3
         XIDEN(K1,K2)=0.0D0
        END DO
      END DO
C 
      DO K1=1,3
         XIDEN(K1,K1)=1.0D0
      ENDDO
C
C     VECTOR INITIALISATION
C 
      FF=0.0D0
      ETOT1=0.0D0
      ETOT0=0.0D0
      SS0=0.0D0
      STR=0.0D0
      SSI=0.0D0
      SS1=0.0D0
      DSS1=0.0D0
      EPLAS0=0.0D0
      EPLAS1=0.0D0
      DYDS=0.0D0
      FFS=0.0D0
      NP=0.0D0
      DNPDK=0.0D0
      RR=0.0D0
      DRRDK=0.0D0
      DHDS=0.0D0
      RRR=0.0D0
      RRI=0.0D0
      XXI=0.0D0
      XX1=0.0D0
      DDD=0.0D0
      J12=0.0D0
      J21=0.0D0
C
      XIDENV=0.0D0
C 
      DO K1=1,3
         XIDENV(K1)=1.0D0
      ENDDO  
C
C     SCALAR INITIALISATION
C 
      ITER=0
      ITERL=0
      FLAG=1
      K1=0
      K2=0
      MM=0.0D0
      ETA=0.0D0
      RDY=0.0D0
      KAPPA0=0.0D0
      DKAPPAI=0.0D0
      DKAPPA1=0.0D0
      DDK1=0.0D0
      KAPPA1=0.0D0
      YSTR=0.0D0
      YS=0.0D0
      DYDK=0.0D0
      DMG=0.0D0
      DMG0=0.0D0
      DDMG=0.0D0
      RAD=0.0D0
      DRAD=0.0D0
      SFFS=0.0D0
      HI=0.0D0
      DHDK=0.0D0
      NORMRR=0.0D0
      ABSY=1.0D0
      KSLOPE=1.0D0
      KMAX=1.0D0
      KWIDTH=1.0D0
      KONSTD=0.0D0
      CRITD=0.0D0
      RHO=0.0D0
      S0=0.0D0
      ETAL=0.0D0
      BETA=0.0D0
      MKI=0.0D0
      MK1=0.0D0
      ALPHA1=0.0D0
      ALPHA2=0.0D0
      ALPHA=0.0D0
      AUX=0.0D0
      UPLIM=0.0D0
      DMK=0.0D0
      J22=0.0D0
      DELTA=0.0D0
C
C     TOLERANCE OF NUMERICAL ERROR  
C 
      TOL=1.0D-12
C
C     MAXIMUM ITERATIONS ALLOWED  
C 
      MAXITER=100
C
C     INPUTFILE PARAMETERS
C
      BF=PROPS(1)
      RHO=PROPS(2)
      MM1=PROPS(3)
      MM2=PROPS(4)
      MM3=PROPS(5)
C
C     VISCOPLASTICITY PARAMETERS
C 
      ETA=1.D-4
      MM=1.0D0
C
C     LINE SEARCH PARAMETERS
C
      BETA=1.D-4
      ETAL=0.25D0
C
C     DAMAGE PARAMETERS (WOLFRAM J BIOMECH 2011)
C 
      KONSTD=8.0075D0
      CRITD=0.85D0
C
C     YIELD/STRENGTH RATIO
C
      RDY=0.7D0
C
C     POSTYIELD PARAMETERS
C
C     KMAX=0.015D0
C     KSLOPE=500.0D0
      KMAX=0.015D0
      KSLOPE=1000.0D0
C     KWIDTH=8.0D0
C     KMAX=0.047D0
C     KSLOPE=100.0D0
      KWIDTH=8.0D0
      KMIN = 0.1D0
      GMIN = -2.0D0
      EXPS = 300.0D0
      ND = 2.0D0
C
C     DENSITY-BASED DENSIFICATION PARAMETERS
C
      ECRIT = -0.3D0
      GAMMAL0 = 1100.0D0
      RL = 2.928D0
      GAMMAP0 = 1300.0D0
      RP = 2.77D0
      POWERDNS = 6.0D0
C
C     BONE TYPES
C
      IF (BF==0) THEN
C     __________________________________________________________________
C
C     DENSITY-BASED ISOTROPIC TRABECULAR BONE
C     __________________________________________________________________
C
C
C     ELASTICITY PARAMETERS 
C     (ISOTROPIC RINCON, PHZ 2012)
C
      E0=6614.07D0
      V0=0.2462D0
      KS=1.333D0
C     MAP TO E0MAX=24128.2
      DELTA=3.65D0
C
C     PLASTIC AND DAMAGE PROPERTIES
C
C     STRENGTH PARAMETERS 
C     (ISOTROPIC RINCON, PHZ 2012)
C     
      SIGD0P=54.7953D0
      SIGD0N=72.8777D0 
      TAUD0=39.9627D0
      ZETA0=0.225D0
      PP=KS
C
C     FLAGS
C
      DENSFL=0
      VISCFL=0
      PYFL=0
C
C     ISOTROPIC COMPLIANCE TENSOR CCCC
C
      MU0=E0/2.0D0/(1.0D0+V0)  
C
      CCCC(1,1)=1.0D0/E0
      CCCC(2,2)=1.0D0/E0
      CCCC(3,3)=1.0D0/E0
      CCCC(4,4)=0.5D0/MU0
      CCCC(5,5)=0.5D0/MU0
      CCCC(6,6)=0.5D0/MU0
      CCCC(2,1)=-V0/E0
      CCCC(3,1)=-V0/E0
      CCCC(3,2)=-V0/E0
      CCCC(1,2)=CCCC(2,1)
      CCCC(1,3)=CCCC(3,1)
      CCCC(2,3)=CCCC(3,2)
C
      CCCC=CCCC/TSFU(RHO,KS,DELTA)
C
C     ISOTROPIC STIFFNESS TENSOR SSSS
C
      CALL MIGS(CCCC,6,SSSS)
C
C     ISOTROPIC QUADRIC FOURTH ORDER TENSOR FFFF
C 
      S0=(SIGD0P+SIGD0N)/2.0D0/SIGD0P/SIGD0N
C      TAUD0=DSQRT(0.5D0/S0**2/(1.0D0+ZETA0))
C
      FFFF(1,1)=S0**2
      FFFF(2,2)=S0**2
      FFFF(3,3)=S0**2
      FFFF(1,2)=-ZETA0*S0**2
      FFFF(1,3)=-ZETA0*S0**2
      FFFF(2,3)=-ZETA0*S0**2
      FFFF(2,1)=FFFF(1,2)
      FFFF(3,1)=FFFF(1,3)
      FFFF(3,2)=FFFF(2,3)
      FFFF(4,4)=0.5D0/TAUD0**2
      FFFF(5,5)=0.5D0/TAUD0**2
      FFFF(6,6)=0.5D0/TAUD0**2
C
      FFFF=FFFF/TSFU(RHO,PP,DELTA)/TSFU(RHO,PP,DELTA)
C 
C     ISOTROPIC QUADRIC SECOND ORDER TENSOR FF
C
      FF(1)=-(SIGD0P-SIGD0N)/2.0D0/SIGD0P/SIGD0N
      FF(2)=-(SIGD0P-SIGD0N)/2.0D0/SIGD0P/SIGD0N
      FF(3)=-(SIGD0P-SIGD0N)/2.0D0/SIGD0P/SIGD0N
      FF(4)=0.0D0
      FF(5)=0.0D0
      FF(6)=0.0D0
C
      FF=FF/TSFU(RHO,PP,DELTA)
C
      ELSE IF (BF==1) THEN
C
C     __________________________________________________________________
C
C     DENSITY-BASED TRANSVERSELY ISOTROPIC TRABECULAR BONE
C     __________________________________________________________________
C
C
C     ELASTICITY PARAMETERS (TIRGWTB, PHZ, 2013)
C 
      E0=6561.94D0
      E33=18661.3D0
      V0=0.323D0
      V30=0.32D0
      MU30=3739.02D0
      KS=1.63D0
      DELTA=1.0D0
C
C     PLASTIC AND DAMAGE PROPERTIES
C
C     STRENGTH PARAMETERS (TIRGWTB, PHZ, 2013)
C 
      SIGD0P=50.63D0
      SIGD0N=68.07D0
      SIGD3P=98.68D0
      SIGD3N=165.80D0
      ZETA0=0.4707D0
      ZETA30=0.1809D0
      TAUD30=51.62D0
      PP=1.69D0
C
C     FLAGS
C
C     DENSFL=1
C     VISCFL=1
C     PYFL=2
C
C     TRANSVERSELY ISOTROPIC COMPLIANCE TENSOR CCCC
C
      MU0=E0/2.0D0/(1.0D0+V0) 
C
      CCCC(1,1)=1.0D0/E0
      CCCC(2,2)=1.0D0/E0
      CCCC(3,3)=1.0D0/E33
      CCCC(4,4)=0.5D0/MU0
      CCCC(5,5)=0.5D0/MU30
      CCCC(6,6)=0.5D0/MU30
      CCCC(2,1)=-V0/E0
      CCCC(3,1)=-V30/E33
      CCCC(3,2)=-V30/E33
      CCCC(1,2)=CCCC(2,1)
      CCCC(1,3)=CCCC(3,1)
      CCCC(2,3)=CCCC(3,2)
C
      CCCC=CCCC/TSFU(RHO,KS,DELTA)
C
C     TRANSVERSELY ISOTROPIC STIFFNESS TENSOR SSSS
C
      CALL MIGS(CCCC,6,SSSS)
C
C     TRANSVERSELY ISOTROPIC QUADRIC FOURTH ORDER TENSOR FFFF
C 
      S0=(SIGD0P+SIGD0N)/2.0D0/SIGD0P/SIGD0N
      S3=(SIGD3P+SIGD3N)/2.0D0/SIGD3P/SIGD3N
C
      TAUD0=DSQRT(0.5D0/S0**2/(1.0D0+ZETA0))
C
      FFFF(1,1)=S0**2
      FFFF(2,2)=S0**2
      FFFF(3,3)=S3**2
      FFFF(1,2)=-ZETA0*S0**2
      FFFF(1,3)=-ZETA30*S3**2
      FFFF(2,3)=-ZETA30*S3**2
      FFFF(2,1)=FFFF(1,2)
      FFFF(3,1)=FFFF(1,3)
      FFFF(3,2)=FFFF(2,3)
      FFFF(4,4)=0.5D0/TAUD0**2
      FFFF(5,5)=0.5D0/TAUD30**2
      FFFF(6,6)=0.5D0/TAUD30**2
C
      FFFF=FFFF/TSFU(RHO,PP,DELTA)/TSFU(RHO,PP,DELTA)
C 
C     TRANSVERSELY ISOTROPIC QUADRIC SECOND ORDER TENSOR FF
C
      FF(1)=-(SIGD0P-SIGD0N)/2.0D0/SIGD0P/SIGD0N
      FF(2)=-(SIGD0P-SIGD0N)/2.0D0/SIGD0P/SIGD0N
      FF(3)=-(SIGD3P-SIGD3N)/2.0D0/SIGD3P/SIGD3N
      FF(4)=0.0D0
      FF(5)=0.0D0
      FF(6)=0.0D0
C
      FF=FF/TSFU(RHO,PP,DELTA)
C
      ELSE IF (BF==2) THEN
C     __________________________________________________________________
C
C     FABRIC- AND DENSITY-BASED ORTHOTROPIC TRABECULAR BONE
C     __________________________________________________________________
C
C     ELASTICITY PARAMETERS 
C     (ISOTROPIC RINCON, PHZ 2012)
C
      E0 = 6614.07D0
      V0 = 0.2462D0
      MU0 = 2654.0D0
      KS = 1.333D0
      LS = 1.0D0
C     MAP TO E0MAX=24128.2
      DELTA = 3.65D0
C
C     PLASTIC AND DAMAGE PROPERTIES
C
C     STRENGTH PARAMETERS 
C     (ISOTROPIC RINCON, PHZ 2012)
C     
      SIGD0P = 54.7953D0
      SIGD0N = 72.8777D0 
      TAUD0  = 44.6339D0
      ZETA0  = 0.333D0
      PP = KS
      QQ = LS
C
C     FLAGS
C
C     DENSFL=1
C     VISCFL=1
C     PYFL=1
C
C     FABRIC-BASED ORTHOTROPIC STIFFNESS TENSOR SSSS
C 
      SSSS(1,1)=E0*(1.0D0-V0)/(1.0D0+V0)/(1.0D0-2.0D0*V0)*MM1
     1   **(2.0D0*LS)*TSFU(RHO,KS,DELTA)
      SSSS(2,2)=E0*(1.0D0-V0)/(1.0D0+V0)/(1.0D0-2.0D0*V0)*MM2
     1   **(2.0D0*LS)*TSFU(RHO,KS,DELTA)
      SSSS(3,3)=E0*(1.0D0-V0)/(1.0D0+V0)/(1.0D0-2.0D0*V0)*MM3
     1   **(2.0D0*LS)*TSFU(RHO,KS,DELTA)
      SSSS(4,4)=2.0D0*MU0*(MM1**LS)*(MM2**LS)*TSFU(RHO,KS,DELTA)
      SSSS(5,5)=2.0D0*MU0*(MM3**LS)*(MM1**LS)*TSFU(RHO,KS,DELTA)
      SSSS(6,6)=2.0D0*MU0*(MM2**LS)*(MM3**LS)*TSFU(RHO,KS,DELTA)
      SSSS(2,1)=E0*V0/(1.0D0+V0)/(1.0D0-2.0D0*V0)*(MM1**LS)*(MM2**LS)
     1   *TSFU(RHO,KS,DELTA)
      SSSS(3,1)=E0*V0/(1.0D0+V0)/(1.0D0-2.0D0*V0)*(MM3**LS)*(MM1**LS)
     1   *TSFU(RHO,KS,DELTA)
      SSSS(3,2)=E0*V0/(1.0D0+V0)/(1.0D0-2.0D0*V0)*(MM2**LS)*(MM3**LS)
     1   *TSFU(RHO,KS,DELTA)
      SSSS(1,2)=SSSS(2,1)
      SSSS(1,3)=SSSS(3,1)
      SSSS(2,3)=SSSS(3,2)
C
C     FABRIC-BASED COMPLIANCE TENSOR CCCC
C 
      CCCC(1,1)=1.0D0/(E0*(MM1**(2.0D0*LS))*TSFU(RHO,KS,DELTA))
      CCCC(2,2)=1.0D0/(E0*(MM2**(2.0D0*LS))*TSFU(RHO,KS,DELTA))
      CCCC(3,3)=1.0D0/(E0*(MM3**(2.0D0*LS))*TSFU(RHO,KS,DELTA))
      CCCC(4,4)=0.5D0/(MU0*(MM1**LS)*(MM2**LS)*TSFU(RHO,KS,DELTA))
      CCCC(5,5)=0.5D0/(MU0*(MM3**LS)*(MM1**LS)*TSFU(RHO,KS,DELTA))
      CCCC(6,6)=0.5D0/(MU0*(MM2**LS)*(MM3**LS)*TSFU(RHO,KS,DELTA))
      CCCC(2,1)=-V0/(E0*(MM1**LS)*(MM2**LS)*TSFU(RHO,KS,DELTA))
      CCCC(3,1)=-V0/(E0*(MM1**LS)*(MM3**LS)*TSFU(RHO,KS,DELTA))
      CCCC(3,2)=-V0/(E0*(MM2**LS)*(MM3**LS)*TSFU(RHO,KS,DELTA))
      CCCC(1,2)=CCCC(2,1)
      CCCC(1,3)=CCCC(3,1)
      CCCC(2,3)=CCCC(3,2)
C
C     FABRIC-BASED QUADRIC FOURTH ORDER TENSOR FFFF
C 
      S0=(SIGD0P+SIGD0N)/2.0D0/SIGD0P/SIGD0N
C
      FFFF(1,1)=S0**2/(TSFU(RHO,PP,DELTA)*MM1**(2.0D0*QQ))**2
      FFFF(2,2)=S0**2/(TSFU(RHO,PP,DELTA)*MM2**(2.0D0*QQ))**2
      FFFF(3,3)=S0**2/(TSFU(RHO,PP,DELTA)*MM3**(2.0D0*QQ))**2
      FFFF(1,2)=-(ZETA0*(MM1/MM2)**(2.0D0*QQ))
     1                 *S0**2/(TSFU(RHO,PP,DELTA)*MM1**(2.0D0*QQ))**2
      FFFF(1,3)=-(ZETA0*(MM1/MM3)**(2.0D0*QQ))
     1                 *S0**2/(TSFU(RHO,PP,DELTA)*MM1**(2.0D0*QQ))**2
      FFFF(2,3)=-(ZETA0*(MM2/MM3)**(2.0D0*QQ))
     1                 *S0**2/(TSFU(RHO,PP,DELTA)*MM2**(2.0D0*QQ))**2
      FFFF(2,1)=FFFF(1,2)
      FFFF(3,1)=FFFF(1,3)
      FFFF(3,2)=FFFF(2,3)
      FFFF(4,4)=0.5D0/((TAUD0*TSFU(RHO,PP,DELTA)*(MM1*MM2)**QQ)**2)
      FFFF(5,5)=0.5D0/((TAUD0*TSFU(RHO,PP,DELTA)*(MM1*MM3)**QQ)**2)
      FFFF(6,6)=0.5D0/((TAUD0*TSFU(RHO,PP,DELTA)*(MM2*MM3)**QQ)**2)
C 
C     FABRIC-BASED QUADRIC SECOND ORDER TENSOR FF
C
      FF(1)=-(SIGD0P-SIGD0N)/2.0D0/SIGD0P/SIGD0N
     1                          /(TSFU(RHO,PP,DELTA)*MM1**(2.0D0*QQ))
      FF(2)=-(SIGD0P-SIGD0N)/2.0D0/SIGD0P/SIGD0N
     1                          /(TSFU(RHO,PP,DELTA)*MM2**(2.0D0*QQ))
      FF(3)=-(SIGD0P-SIGD0N)/2.0D0/SIGD0P/SIGD0N
     1                          /(TSFU(RHO,PP,DELTA)*MM3**(2.0D0*QQ))
      FF(4)=0.0D0
      FF(5)=0.0D0
      FF(6)=0.0D0
C
      ELSE IF (BF==3) THEN
C     __________________________________________________________________
C
C     DENSITY-BASED ISOTROPIC COMPACT BONE
C     __________________________________________________________________
C
C
C     ELASTICITY PARAMETERS (ISORBCT, JJS, 2013)
C 
      E0=19327.0D0
      V0=0.3434D0
      KS=1.63D0
      DELTA=1.0D0
C
C     PLASTIC AND DAMAGE PROPERTIES
C
C     STRENGTH PARAMETERS (ISORBCT, JJS, 2013)
C 
      SIGD0P=144.7D0
      SIGD0N=234.2D0
      ZETA0=0.49
      PP=1.69D0
C
C     FLAGS
C
C     DENSFL=0
C     VISCFL=1
C     PYFL=1
C
C     ISOTROPIC COMPLIANCE TENSOR CCCC
C 
      MU0=E0/2.0D0/(1.0D0+V0)  
C
      CCCC(1,1)=1.0D0/E0
      CCCC(2,2)=1.0D0/E0
      CCCC(3,3)=1.0D0/E0
      CCCC(4,4)=0.5D0/MU0
      CCCC(5,5)=0.5D0/MU0
      CCCC(6,6)=0.5D0/MU0
      CCCC(2,1)=-V0/E0
      CCCC(3,1)=-V0/E0
      CCCC(3,2)=-V0/E0
      CCCC(1,2)=CCCC(2,1)
      CCCC(1,3)=CCCC(3,1)
      CCCC(2,3)=CCCC(3,2)
C
      CCCC=CCCC/TSFU(RHO,KS,DELTA)
C
C     ISOTROPIC STIFFNESS TENSOR SSSS
C
      CALL MIGS(CCCC,6,SSSS)
C
C     ISOTROPIC QUADRIC FOURTH ORDER TENSOR FFFF
C 
      S0=(SIGD0P+SIGD0N)/2.0D0/SIGD0P/SIGD0N
      TAUD0=DSQRT(0.5D0/S0**2/(1.0D0+ZETA0))
C
      FFFF(1,1)=S0**2
      FFFF(2,2)=S0**2
      FFFF(3,3)=S0**2
      FFFF(1,2)=-ZETA0*S0**2
      FFFF(1,3)=-ZETA0*S0**2
      FFFF(2,3)=-ZETA0*S0**2
      FFFF(2,1)=FFFF(1,2)
      FFFF(3,1)=FFFF(1,3)
      FFFF(3,2)=FFFF(2,3)
      FFFF(4,4)=0.5D0/TAUD0**2
      FFFF(5,5)=0.5D0/TAUD0**2
      FFFF(6,6)=0.5D0/TAUD0**2
C
      FFFF=FFFF/TSFU(RHO,PP,DELTA)/TSFU(RHO,PP,DELTA)
C 
C     ISOTROPIC QUADRIC SECOND ORDER TENSOR FF
C
      FF(1)=-(SIGD0P-SIGD0N)/2.0D0/SIGD0P/SIGD0N
      FF(2)=-(SIGD0P-SIGD0N)/2.0D0/SIGD0P/SIGD0N
      FF(3)=-(SIGD0P-SIGD0N)/2.0D0/SIGD0P/SIGD0N
      FF(4)=0.0D0
      FF(5)=0.0D0
      FF(6)=0.0D0
C
      FF=FF/TSFU(RHO,PP,DELTA)
C
      ELSE IF (BF==4) THEN
C     __________________________________________________________________
C
C     DENSITY-BASED TRANSVERSELY ISOTROPIC COMPACT BONE
C     __________________________________________________________________
C
C
C     ELASTICITY PARAMETERS (TIRBCT, JJS, 2013)
C 
      E0=15079.6D0
      E33=24578.5D0
      V0=0.4620D0
      V30=0.354D0
      MU30=6578.01D0
      KS=1.63D0
      DELTA=1.0D0
C
C     PLASTIC AND DAMAGE PROPERTIES
C
C     STRENG PARAMETERS (TIRBCT, JJS, 2013)
C 
      SIGD0P=56.54D0
      SIGD0N=201.28D0
      SIGD3P=176.40D0
      SIGD3N=268.00D0
      ZETA0=0.0074D0
      ZETA30=1.4045D0
      TAUD30=82.55D0
      PP=1.686D0
C
C     FLAGS
C
C     DENSFL=0
C     VISCFL=1
C     PYFL=1
C
C     TRANSVERSELY ISOTROPIC COMPLIANCE TENSOR CCCC
C 
      MU0=E0/2.0D0/(1.0D0+V0) 
C
      CCCC(1,1)=1.0D0/E0
      CCCC(2,2)=1.0D0/E0
      CCCC(3,3)=1.0D0/E33
      CCCC(4,4)=0.5D0/MU0
      CCCC(5,5)=0.5D0/MU30
      CCCC(6,6)=0.5D0/MU30
      CCCC(2,1)=-V0/E0
      CCCC(3,1)=-V30/E33
      CCCC(3,2)=-V30/E33
      CCCC(1,2)=CCCC(2,1)
      CCCC(1,3)=CCCC(3,1)
      CCCC(2,3)=CCCC(3,2)
C
      CCCC=CCCC/TSFU(RHO,KS,DELTA)
C
C     TRANSVERSELY ISOTROPIC STIFFNESS TENSOR SSSS
C
      CALL MIGS(CCCC,6,SSSS)
C
C     TRANSVERSELY ISOTROPIC QUADRIC FOURTH ORDER TENSOR FFFF
C 
      S0=(SIGD0P+SIGD0N)/2.0D0/SIGD0P/SIGD0N
      S3=(SIGD3P+SIGD3N)/2.0D0/SIGD3P/SIGD3N
C
      TAUD0=DSQRT(0.5D0/S0**2/(1.0D0+ZETA0))
C
      FFFF(1,1)=S0**2
      FFFF(2,2)=S0**2
      FFFF(3,3)=S3**2
      FFFF(1,2)=-ZETA0*S0**2
      FFFF(1,3)=-ZETA30*S3**2
      FFFF(2,3)=-ZETA30*S3**2
      FFFF(2,1)=FFFF(1,2)
      FFFF(3,1)=FFFF(1,3)
      FFFF(3,2)=FFFF(2,3)
      FFFF(4,4)=0.5D0/TAUD0**2
      FFFF(5,5)=0.5D0/TAUD30**2
      FFFF(6,6)=0.5D0/TAUD30**2
C
      FFFF=FFFF/TSFU(RHO,PP,DELTA)/TSFU(RHO,PP,DELTA)
C 
C     TRANSVERSELY ISOTROPIC QUADRIC SECOND ORDER TENSOR FF
C
      FF(1)=-(SIGD0P-SIGD0N)/2.0D0/SIGD0P/SIGD0N
      FF(2)=-(SIGD0P-SIGD0N)/2.0D0/SIGD0P/SIGD0N
      FF(3)=-(SIGD3P-SIGD3N)/2.0D0/SIGD3P/SIGD3N
      FF(4)=0.0D0
      FF(5)=0.0D0
      FF(6)=0.0D0
C
      FF=FF/TSFU(RHO,PP,DELTA)
C
      END IF
C     __________________________________________________________________
C
C     RECOVER STATE VARIABLES
C 
      ETOT1=STRAN+DSTRAN
      ETOT0=STRAN
C 
C     SET ALL STATE VARIABLES TO ZERO AT THE BEGINNING OF THE SIMULATION
C 
      IF (KSTEP==(1).AND.KINC==(1)) THEN
        DO K1=1,9
          STATEV(K1)=0.0D0
        END DO
      ENDIF
C 
C    SDV 1: CUMULATED PLASTIC STRAIN
C    SDV 2: SCALAR DAMAGAE VARIABLE
C    SDV 3-8: PLASTIC STRAIN VECTOR
C    SDV 9-14: NOMINAL STRESS VECTOR
C    SDV 15-20: DENSIFICATION STRESS VECTOR
C    SDV 21: ORIGINAL BVTV
C    SDV 22: UPDATED BVTV 
     
      KAPPA0=STATEV(1)

      IF (KAPPA0<0.0D0) THEN
        KAPPA0=0.0D0
      ENDIF 
C
C     RECOVER AND ROTATE PLASTIC STRAIN 
C 
      CALL ROTSIG(STATEV( 3),DROT,EPLAS0,2,NDI,NSHR)
C
C     UPDATE BVTV
C
      DETF0 = (2*DFGRD0(1,2)*DFGRD0(1,3)*DFGRD0(2,3)+
     +        DFGRD0(1,1)*DFGRD0(2,2)*DFGRD0(3,3))-
     +       (DFGRD0(1,3)*DFGRD0(1,3)*DFGRD0(2,2)+
     +        DFGRD0(1,1)*DFGRD0(2,3)*DFGRD0(2,3)+
     +        DFGRD0(1,2)*DFGRD0(1,2)*DFGRD0(3,3))
C 
      IF (RHO/DETF0 .GE. 1.0D0) THEN
      STATEV(22) = 1.0D0
      ELSE
      STATEV(22)=RHO/DETF0 
      ENDIF
C 
C     CONVERT INITIAL STRAINS TO VOITH-MANDL NOTATION
C 
      DO K1=4,6
         ETOT1(K1)=ETOT1(K1)/DSQRT(2.0D0)
         ETOT0(K1)=ETOT0(K1)/DSQRT(2.0D0)
         EPLAS0(K1)=EPLAS0(K1)/DSQRT(2.0D0)
      END DO
C
C     STRESS AT THE BEGINNING OF THE CURRENT INCREMENT
C 
      SS0=(1.0D0-DAM(KAPPA0,KONSTD,CRITD))*MATMUL(SSSS,ETOT0-EPLAS0)
C
C     ELASTIC TRIAL STRESS
C 
      STR=(1.0D0-DAM(KAPPA0,KONSTD,CRITD))*MATMUL(SSSS,ETOT1-EPLAS0)
C 
C     YIELD CRITERION WITH TRIAL STRESS
C 
      RAD=RADK(PYFL,KSLOPE,KMAX,KWIDTH,RDY,KAPPA0,KMIN,GMIN,ND,EXPS)
      DRAD=DRADK(PYFL,KSLOPE,KMAX,KWIDTH,RDY,KAPPA0,KMIN,GMIN,ND,EXPS)
      FFS=MATMUL(FFFF,STR)
      SFFS=DOT_PRODUCT(STR,FFS)
C 
      YSTR=DSQRT(SFFS)+DOT_PRODUCT(FF,STR)-RAD
C     __________________________________________________________________
C
C     ELASTIC CASE
C     __________________________________________________________________
C 
      IF (YSTR<=TOL) THEN
C
C       UPDATE STATE VARIABLES
C    
        KAPPA1=KAPPA0
        EPLAS1=EPLAS0 
C
C       ELASTIC STRESS UPDATE
C 
        SS1=STR
C
C       ELASTIC JACOBIAN
C 
        TANM=(1.0D0-DAM(KAPPA0,KONSTD,CRITD))*SSSS
C     __________________________________________________________________
C
C     INELASTIC CASE
C     __________________________________________________________________ 
C 
      ELSE IF (YSTR>TOL) THEN
C    
        ITER=0
        EPLAS1=EPLAS0
        DKAPPA1=0.0D0
        KAPPA1=KAPPA0+DKAPPA1
        SS1=STR
C 
        DMG=DAM(KAPPA1,KONSTD,CRITD)
        DMG0=DAM(KAPPA0,KONSTD,CRITD)
        DDMG=DDAM(KAPPA1,KONSTD,CRITD)
        RAD=RADK(PYFL,KSLOPE,KMAX,KWIDTH,RDY,KAPPA1,KMIN,GMIN,ND,EXPS)
        DRAD=DRADK(PYFL,KSLOPE,KMAX,KWIDTH,RDY,KAPPA1,KMIN,GMIN,ND
     1                                                          ,EXPS)
C 
        FFS=MATMUL(FFFF,SS1)
        SFFS=DOT_PRODUCT(SS1,FFS)
C
        DSY=1.0D0/DSQRT(SFFS)*FFS+FF
        DDSY=-1.0D0*(SFFS)**(-1.5D0)*VECDYAD(FFS,FFS)
     1                                          +1.0D0/DSQRT(SFFS)*FFFF
C
        HI=VECNORM(DSY)
        NP=DSY/HI
C 
        YS=DSQRT(SFFS)+DOT_PRODUCT(FF,SS1)-RAD
     1                           +VISCY(VISCFL,ETA,MM,DTIME,DKAPPA1,HI)
        RR=-MATMUL(CCCC,SS1-STR)/(1.0D0-DMG)-(DMG-DMG0)/(1.0D0-DMG)
     1                                       *(ETOT1-EPLAS0)-DKAPPA1*NP
C   
        ABSY=DABS(YS)
        NORMRR=VECNORM(RR)
C
C     __________________________________________________________________
C
C         NEWTON CLOSEST POINT PROJECTION W/O LINE SEARCH
C     __________________________________________________________________ 
C
C   
        DO WHILE ((NORMRR>TOL.OR.ABSY>TOL).AND.ITER<=10)
C 
          ITER=ITER+1 
C 
          SSI=SS1
          DKAPPAI=DKAPPA1
C 
          DHDS=1.0D0/DSQRT(DOT_PRODUCT(DSY,DSY))*MATMUL(DDSY,DSY)
          DHDK=0.0D0
          DYDS=DSY+VDYDS(VISCFL,ETA,MM,DTIME,DKAPPAI,DHDS,HI)
          DYDK=-DRAD+VDYDK(VISCFL,ETA,MM,DTIME,DKAPPAI,DHDK,HI)
          DNPDS=(DDSY*HI-VECDYAD(DSY,DHDS))/HI**2
          DNPDK=0.0D0
C
          DRRDS=-CCCC/(1.0D0-DMG)-DKAPPAI*DNPDS
          DRRDK=-DDMG/(1.0D0-DMG)**2*(MATMUL(CCCC,SSI-STR)+(1.0D0
     1                          -DMG0)*(ETOT1-EPLAS0))-NP-DKAPPAI*DNPDK
C 
          CALL MIGS(-DRRDS,6,SSSA)
C 
          DDK1=-(YS/VECNORM(DYDS)+DOT_PRODUCT(NP,MATMUL(SSSA,RR)))
     1                             /(DOT_PRODUCT(NP,MATMUL(SSSA,DRRDK))
     2                                             +DYDK/VECNORM(DYDS))
C 
          DSS1=MATMUL(SSSA,(RR+DRRDK*DDK1))
C 
          SS1=SSI+DSS1
C 
          DKAPPA1=DKAPPAI+DDK1
C 
C         IF DKAPPA1 BECOMES SMALLER THAN 0 AND THEREFORE INADMISSIBLE,
C         RESTART THE NEWTON SCHEME WITH A DIFFERENT STARTING POINT
C 
          IF (DKAPPA1<0.0D0) THEN
            SS1=STR
            DKAPPA1=0.0D0
          END IF
C 
          KAPPA1=KAPPA0+DKAPPA1
C
C         CHECK RESIDUAL AND YIELD CRITERION AT I+1 FOR ITERATION BREAK
C 
          DMG=DAM(KAPPA1,KONSTD,CRITD)
          DDMG=DDAM(KAPPA1,KONSTD,CRITD)
          RAD=RADK(PYFL,KSLOPE,KMAX,KWIDTH,RDY,KAPPA1,KMIN,GMIN,ND
     1                                                           ,EXPS)
          DRAD=DRADK(PYFL,KSLOPE,KMAX,KWIDTH,RDY,KAPPA1,KMIN,GMIN,ND
     1                                                           ,EXPS) 
          FFS=MATMUL(FFFF,SS1)
          SFFS=DOT_PRODUCT(SS1,FFS)
C
          DSY=1.0D0/DSQRT(SFFS)*FFS+FF
          DDSY=-1.0D0*(SFFS)**(-1.5D0)*VECDYAD(FFS,FFS)
     1                                          +1.0D0/DSQRT(SFFS)*FFFF
C
          HI=VECNORM(DSY)
          NP=DSY/HI
C 
          YS=DSQRT(SFFS)+DOT_PRODUCT(FF,SS1)-RAD
     1                           +VISCY(VISCFL,ETA,MM,DTIME,DKAPPA1,HI)
          RR=-MATMUL(CCCC,SS1-STR)/(1.0D0-DMG)-(DMG-DMG0)/(1.0D0-DMG)
     1                                       *(ETOT1-EPLAS0)-DKAPPA1*NP
C 
          NORMRR=VECNORM(RR)
          ABSY=DABS(YS)
C 
        END DO 
C     __________________________________________________________________
C
C         PRIMAL CPPA FOR GLOBAL CONVERGENCE
C     __________________________________________________________________ 
C
        IF (ITER.GT.10.AND.(NORMRR.GT.TOL.OR.ABSY.GT.TOL)) THEN 
C
          ITER=0
          EPLAS1=EPLAS0
          DKAPPA1=0.0D0
          KAPPA1=KAPPA0+DKAPPA1
          SS1=STR
C 
          DMG=DAM(KAPPA1,KONSTD,CRITD)
          DMG0=DAM(KAPPA0,KONSTD,CRITD)
          DDMG=DDAM(KAPPA1,KONSTD,CRITD)
          RAD=RADK(PYFL,KSLOPE,KMAX,KWIDTH,RDY,KAPPA1,KMIN,GMIN,ND
     1                                                           ,EXPS)
          DRAD=DRADK(PYFL,KSLOPE,KMAX,KWIDTH,RDY,KAPPA1,KMIN,GMIN,ND
     1                                                           ,EXPS)
C 
          FFS=MATMUL(FFFF,SS1)
          SFFS=DOT_PRODUCT(SS1,FFS)
C
          DSY=1.0D0/DSQRT(SFFS)*FFS+FF
          DDSY=-1.0D0*(SFFS)**(-1.5D0)*VECDYAD(FFS,FFS)
     1                                          +1.0D0/DSQRT(SFFS)*FFFF
C
          HI=VECNORM(DSY)
          NP=DSY/HI
C 
          YS=DSQRT(SFFS)+DOT_PRODUCT(FF,SS1)-RAD
     1                           +VISCY(VISCFL,ETA,MM,DTIME,DKAPPA1,HI)
          RR=-MATMUL(CCCC,SS1-STR)/(1.0D0-DMG)-(DMG-DMG0)/(1.0D0-DMG)
     1                                       *(ETOT1-EPLAS0)-DKAPPA1*NP
C   
          ABSY=DABS(YS)
          NORMRR=VECNORM(RR)
C
          DO K1 = 1,6
            RRI(K1) = RR(K1)
          ENDDO
            RRI(7)=YS
C
          DO WHILE ((NORMRR>TOL.OR.ABSY>TOL).AND.ITER<=MAXITER)
C 
            ITER=ITER+1 
C 
            SSI=SS1
            DKAPPAI=DKAPPA1
C 
            DHDS=1.0D0/DSQRT(DOT_PRODUCT(DSY,DSY))*MATMUL(DDSY,DSY)
            DHDK=0.0D0
            DYDS=DSY+VDYDS(VISCFL,ETA,MM,DTIME,DKAPPAI,DHDS,HI)
            DYDK=-DRAD+VDYDK(VISCFL,ETA,MM,DTIME,DKAPPAI,DHDK,HI)
            DNPDS=(DDSY*HI-VECDYAD(DSY,DHDS))/HI**2
            DNPDK=0.0D0
C
            DRRDS=-CCCC/(1.0D0-DMG)-DKAPPAI*DNPDS
            DRRDK=-DDMG/(1.0D0-DMG)**2*(MATMUL(CCCC,SSI-STR)+(1.0D0
     1                          -DMG0)*(ETOT1-EPLAS0))-NP-DKAPPAI*DNPDK
C 
C           BUILD SYSTEM RESIDUAL VECTOR
C
            DO K1 = 1,6
              RRR(K1) = RR(K1)
            ENDDO
            RRR(7)=YS
C
            J11=DRRDS
            J22=DYDK
            J12=DRRDK
            J21=DYDS
C
C           BUILD SYSTEM JACOBIAN
C
            DO K1 = 1,6
              DO K2 = 1,6
                JJJ(K1,K2) = J11(K1,K2)
              ENDDO
              JJJ(7,K1)=J21(K1)
              JJJ(K1,7)=J12(K1)
            ENDDO
            JJJ(7,7)=J22
C
C           INVERT SYSTEM JACOBIAN
C
            CALL MIGS(JJJ,7,INVJ)
C
            AUX=0.0D0
            IF (DKAPPA1.EQ.0.0D0) THEN
              AUX=DOT_PRODUCT(NP,(SS1-STR))
            END IF
C
C           DETERMINE SYSTEM UPDATES
C
            IF (AUX.LE.0.0D0) THEN
C
              FLAG=1
C
              DDD=MATMUL(-INVJ,RRR)
C
            ELSE
C
              FLAG=0
C
              DDJ=MATMUL(INVJ,TRANSPOSE(INVJ))
              DO K1 = 1,6
                DDJ(7,K1)=0.0D0
                DDJ(K1,7)=0.0D0
              ENDDO
C
              DDD=MATMUL(-MATMUL(DDJ,TRANSPOSE(JJJ)),RRR)
C
            END IF  
C
C           RECOVER STRESS AND KAPPA UPDATE
C
            DO K1 = 1,6
              DSS1(K1)=DDD(K1)
            ENDDO
            DDK1=DDD(7)            
C 
            SS1=SSI+DSS1
            DKAPPA1=DKAPPAI+DDK1
C
            DO K1 = 1,6
              XXI(K1)=SS1(K1)
            ENDDO
            XXI(7)=DKAPPA1
C 
C           ENFORCE CONSTRAIN DKAPPA >= 0.0D0
C
            IF (DKAPPA1<0.0D0) THEN
              DKAPPA1=0.0D0
            END IF
C 
            KAPPA1=KAPPA0+DKAPPA1
C
C           CHECK RESIDUAL AND YIELD CRITERION AT I+1 FOR ITERATION BREAK
C 
            DMG=DAM(KAPPA1,KONSTD,CRITD)
            DDMG=DDAM(KAPPA1,KONSTD,CRITD)
            RAD=RADK(PYFL,KSLOPE,KMAX,KWIDTH,RDY,KAPPA1,KMIN,GMIN,ND
     1                                                           ,EXPS)
            DRAD=DRADK(PYFL,KSLOPE,KMAX,KWIDTH,RDY,KAPPA1,KMIN,GMIN,ND
     1                                                           ,EXPS)
            FFS=MATMUL(FFFF,SS1)
            SFFS=DOT_PRODUCT(SS1,FFS)
C
            DSY=1.0D0/DSQRT(SFFS)*FFS+FF
            DDSY=-1.0D0*(SFFS)**(-1.5D0)*VECDYAD(FFS,FFS)
     1                                          +1.0D0/DSQRT(SFFS)*FFFF
C
            HI=VECNORM(DSY)
            NP=DSY/HI
C 
C           LINE SEARCH MERIT FUNCTION AND DERIVATIVE OF ITERATION I
C
            MKI=0.5D0*(DOT_PRODUCT(RR,RR)+YS**2)
C
            IF (FLAG.EQ.1) THEN
              DMK=-2.0D0*MKI
            ELSE
              DMK=DOT_PRODUCT(RRR,MATMUL(JJJ,DDD))
            END IF
C           
C           RESIDUAL AND LINE SEARCH MERIT FUNCTION OF ITERATION I+1
C     
            YS=DSQRT(SFFS)+DOT_PRODUCT(FF,SS1)-RAD
     1                           +VISCY(VISCFL,ETA,MM,DTIME,DKAPPA1,HI)
            RR=-MATMUL(CCCC,SS1-STR)/(1.0D0-DMG)-(DMG-DMG0)/(1.0D0-DMG)
     1                                       *(ETOT1-EPLAS0)-DKAPPA1*NP
C
            DO K1 = 1,6
              RRR(K1) = RR(K1)
            ENDDO
            RRR(7)=YS
C
            MK1=0.5D0*(DOT_PRODUCT(RR,RR)+YS**2)
C
C           LINE SEARCH ALGORITHM FOR CONSTRAINED PROBLEMS (ARMERO 2002)
C
C
            IF (FLAG.EQ.1.AND.DKAPPA1.GE.0.0D0) THEN
              UPLIM=(1.0D0-2.0D0*BETA*ALPHA)*MKI
            ELSE
              UPLIM=MKI+BETA*DOT_PRODUCT(RRR,MATMUL(JJJ,XX1-XXI))
            END IF
C
            IF (MK1.GT.UPLIM) THEN
C
              ITERL=0
              ALPHA=1.0D0
              XX1=XXI
C
              DO WHILE (MK1.GT.UPLIM.AND.ALPHA.GE.BETA.AND.ITERL.LT.20)
C
                ITERL=ITERL+1
C
                ALPHA1=ETAL*ALPHA
                ALPHA2=-ALPHA**2*DMK/2.0D0/(MK1-MKI-ALPHA*DMK)
C
                IF (ALPHA1.GE.ALPHA2) THEN
                  ALPHA=ALPHA1
                ELSE
                  ALPHA=ALPHA2
                END IF
C
                DKAPPA1=DKAPPAI+ALPHA*DDK1
C
                IF (DKAPPA1<0.0D0) THEN
                  DKAPPA1=0.0D0
                END IF

                KAPPA1=KAPPA0+DKAPPA1
                SS1=SSI+ALPHA*DSS1
C
                DO K1 = 1,6
                  XX1(K1)=SS1(K1)
                ENDDO
                XX1(7)=DKAPPA1
C
                DMG=DAM(KAPPA1,KONSTD,CRITD)
                RAD=RADK(PYFL,KSLOPE,KMAX,KWIDTH,RDY,KAPPA1,KMIN,GMIN
     1                                                        ,ND,EXPS)
                FFS=MATMUL(FFFF,SS1)
                SFFS=DOT_PRODUCT(SS1,FFS)
                DSY=1.0D0/DSQRT(SFFS)*FFS+FF
                HI=VECNORM(DSY)
                NP=DSY/HI
C   
                YS=DSQRT(SFFS)+DOT_PRODUCT(FF,SS1)-RAD
     1                           +VISCY(VISCFL,ETA,MM,DTIME,DKAPPA1,HI)
                RR=-MATMUL(CCCC,SS1-STR)/(1.0D0-DMG)-(DMG-DMG0)
     1                          /(1.0D0-DMG)*(ETOT1-EPLAS0)-DKAPPA1*NP
C
                DO K1 = 1,6
                  RRR(K1) = RR(K1)
                ENDDO
                RRR(7)=YS
C
                MK1=0.5D0*(DOT_PRODUCT(RR,RR)+YS**2)
C
                IF (FLAG.EQ.1.AND.DKAPPA1.GE.0.0D0) THEN
                  UPLIM=(1.0D0-2.0D0*BETA*ALPHA)*MKI
                ELSE
                  UPLIM=MKI+BETA*DOT_PRODUCT(RRI,MATMUL(JJJ,XX1-XXI))
                END IF
C       
              END DO
C
              DMG=DAM(KAPPA1,KONSTD,CRITD)
              DDMG=DDAM(KAPPA1,KONSTD,CRITD)
              RAD=RADK(PYFL,KSLOPE,KMAX,KWIDTH,RDY,KAPPA1,KMIN,GMIN
     1                                                        ,ND,EXPS)
              DRAD=DRADK(PYFL,KSLOPE,KMAX,KWIDTH,RDY,KAPPA1,KMIN
     1                                                   ,GMIN,ND,EXPS)
              FFS=MATMUL(FFFF,SS1)
              SFFS=DOT_PRODUCT(SS1,FFS)
C
              DSY=1.0D0/DSQRT(SFFS)*FFS+FF
              DDSY=-1.0D0*(SFFS)**(-1.5D0)*VECDYAD(FFS,FFS)
     1                                          +1.0D0/DSQRT(SFFS)*FFFF
C
              HI=VECNORM(DSY)
              NP=DSY/HI
C         
              YS=DSQRT(SFFS)+DOT_PRODUCT(FF,SS1)-RAD
     1                           +VISCY(VISCFL,ETA,MM,DTIME,DKAPPA1,HI)
              RR=-MATMUL(CCCC,SS1-STR)/(1.0D0-DMG)-(DMG-DMG0)
     1                          /(1.0D0-DMG)*(ETOT1-EPLAS0)-DKAPPA1*NP
C
              DO K1 = 1,6
                RRI(K1) = RR(K1)
              ENDDO
              RRI(7)=YS
C
            END IF
C 
            NORMRR=VECNORM(RR)
            ABSY=DABS(YS)
C 
          END DO
        END IF
C 
C
C       TANGENT STIFFNESS MATRIX
C
        DMG=DAM(KAPPA1,KONSTD,CRITD)
        DDMG=DDAM(KAPPA1,KONSTD,CRITD)
        RAD=RADK(PYFL,KSLOPE,KMAX,KWIDTH,RDY,KAPPA1,KMIN,GMIN
     1                                                        ,ND,EXPS)
        DRAD=DRADK(PYFL,KSLOPE,KMAX,KWIDTH,RDY,KAPPA1,KMIN
     1                                                   ,GMIN,ND,EXPS)
        FFS=MATMUL(FFFF,SS1)
        SFFS=DOT_PRODUCT(SS1,FFS)
C
        DSY=1.0D0/DSQRT(SFFS)*FFS+FF
        DDSY=-1.0D0*(SFFS)**(-1.5D0)*VECDYAD(FFS,FFS)
     1                                          +1.0D0/DSQRT(SFFS)*FFFF
C
        HI=VECNORM(DSY)
        NP=DSY/HI
C         
        YS=DSQRT(SFFS)+DOT_PRODUCT(FF,SS1)-RAD
     1                           +VISCY(VISCFL,ETA,MM,DTIME,DKAPPA1,HI)
        RR=-MATMUL(CCCC,SS1-STR)/(1.0D0-DMG)-(DMG-DMG0)
     1                          /(1.0D0-DMG)*(ETOT1-EPLAS0)-DKAPPA1*NP
C
        DHDS=1.0D0/DSQRT(DOT_PRODUCT(DSY,DSY))*MATMUL(DDSY,DSY)
        DHDK=0.0D0
        DYDS=DSY+VDYDS(VISCFL,ETA,MM,DTIME,DKAPPAI,DHDS,HI)
        DYDK=-DRAD+VDYDK(VISCFL,ETA,MM,DTIME,DKAPPAI,DHDK,HI)
        DNPDS=(DDSY*HI-VECDYAD(DSY,DHDS))/HI**2
        DNPDK=0.0D0
C
        DRRDS=-CCCC/(1.0D0-DMG)-DKAPPAI*DNPDS
        DRRDK=-DDMG/(1.0D0-DMG)**2*(MATMUL(CCCC,SSI-STR)+(1.0D0
     1                          -DMG0)*(ETOT1-EPLAS0))-NP-DKAPPAI*DNPDK
C 
        CALL MIGS(-DRRDS,6,SSSA)
C 
        TANM=SSSA-MATMUL(MATMUL(SSSA,VECDYAD(DRRDK,NP)),SSSA)
     1         /(DOT_PRODUCT(NP,MATMUL(SSSA,DRRDK))+DYDK/VECNORM(DYDS))
C 
C       FINAL PLASTIC STRAIN
C 
        EPLAS1=ETOT1-MATMUL(CCCC,SS1)/(1.0D0-DAM(KAPPA1,KONSTD,CRITD))
C 
      END IF
C
C     CHECK FOR CONVERGENCE OF BACK PROJECTION ALGORITHM
C 
      IF (YSTR>=0.0D0.AND.ITER>MAXITER) THEN
        WRITE(*,*) 'HIGH NUMBER OF ITERATIONS NEEDED'
        WRITE(*,*) 'Step : ',KSTEP
        WRITE(*,*) 'Inc : ',KINC
        WRITE(*,*) 'Elem : ',NOEL
        WRITE(*,*) 'Point : ',NPT
        WRITE(*,*) 'THE INCREMENT SIZE WILL BE REDUCED BY 50%'
        PNEWDT=0.5
        KAPPA1=KAPPA0
        EPLAS1=EPLAS0
        SS1=STR
        TANM=(1.0D0-DAM(KAPPA0,KONSTD,CRITD))*SSSS
      END IF
C
      DO K1 = 1,6
        STATEV(8+K1) = SS1(K1)
      ENDDO
C     __________________________________________________________________
C
C     DENSIFICATION ROUTINE          
C     __________________________________________________________________
C 
      IF (DENSFL.EQ.1) THEN
C     __________________________________________________________________
C
C     CALCULATE THE DENSIFICATION STRESS AND TANGENT           
C     __________________________________________________________________
C 
        TRACEEN = ETOT1(1)+ETOT1(2)+ETOT1(3)
C 
        CRITERION = TRACEEN-ECRIT
C 
        IF (CRITERION .LE. 0.0D0) THEN
C 
        GAMMAL = GAMMAL0*(RHO**RL)
        GAMMAP = GAMMAP0*(RHO**RP)
C 
          DO K1=1,3
            DO K2=1,3
              SDNST(K1,K2) = (GAMMAL*CRITERION+GAMMAP*
     1            CRITERION**(POWERDNS-1.0D0))*XIDEN(K1,K2)
            ENDDO
          ENDDO
C     __________________________________________________________________
C
C     UPDATING THE NOMINAL STRESS TENSOR BY  
C     ADDING THE  DENSIFICATION STRESS     
C     __________________________________________________________________
C 
          DO K1 =1,3
            SS1(K1)=SS1(K1)+SDNST(K1,K1)
            SDNS(K1)=SDNST(K1,K1)
          ENDDO
C 
          SDNS(4)=SDNST(1,2)
          SDNS(5)=SDNST(1,3)
          SDNS(6)=SDNST(2,3)
C 
          SS1(4)=SS1(4)+SDNST(1,2)*DSQRT(2.0D0)
          SS1(5)=SS1(5)+SDNST(1,3)*DSQRT(2.0D0)
          SS1(6)=SS1(6)+SDNST(2,3)*DSQRT(2.0D0)
C
C     __________________________________________________________________
C
C     UPDATING THE NOMINAL JACOBIAN 
C     (ADDING THE DENSIFICATOR TANGENT STIFFNESS)     
C     __________________________________________________________________
C 
          XDENSSTIFF1 = (GAMMAL+GAMMAP*(POWERDNS-1.0D0)*
     1              CRITERION**(POWERDNS-2.0D0))
C 
          TANGDENS=XDENSSTIFF1*VECDYAD(XIDENV,XIDENV)   
C 
          TANM=TANM+TANGDENS 
C 
        ENDIF
C 
C     __________________________________________________________________
C
C     END OF DENSIFICATION ROUTINE               
C     __________________________________________________________________
C 
        DO K1 = 1,6
          STATEV(14+K1) = SDNS(K1)
        ENDDO
C
      ENDIF
C 
C     __________________________________________________________________
C
C     RETURN VARIABLES TO ABAQUS 
C     __________________________________________________________________
C
C     DISSIPATION (PLASTICITY AND DAMAGE)
C
      SPD=SPD+DOT_PRODUCT((SS0+SS1)/2.0D0,EPLAS1-EPLAS0)+0.5D0*(0.5D0
     1          *(DDAM(KAPPA1,KONSTD,CRITD)+DDAM(KAPPA0,KONSTD,CRITD)))
     2                *DOT_PRODUCT((0.5D0*(ETOT1-EPLAS1+ETOT0-EPLAS0)),
     3                MATMUL(SSSS,(0.5D0*(ETOT1-EPLAS1+ETOT0-EPLAS0))))
     4                                                 *(KAPPA1-KAPPA0)
C
C     CREEP DISSIPATION
C
      SCD=0.0D0
C
C     CONVERT TANGENT STIFFNESS OPERATOR MATRIX TO ABAQUS CONVENTION 
C 
      DO K1=4,6
        DO K2=4,6
          TANM(K1,K2)=TANM(K1,K2)/2.0D0
          TANM(K1-3,K2)=TANM(K1-3,K2)/DSQRT(2.0D0)
          TANM(K1,K2-3)=TANM(K1,K2-3)/DSQRT(2.0D0)
        END DO
      END DO
C     __________________________________________________________________
C
C     CONVERT STRESSES AND STRAINS TO ABAQUS CONVENTION 
C 
      DO K1=4,6
        SS1(K1)=SS1(K1)/DSQRT(2.0D0)
        EPLAS1(K1)=EPLAS1(K1)*DSQRT(2.0D0)
        EPLAS0(K1)=EPLAS0(K1)*DSQRT(2.0D0)
      END DO 
C     __________________________________________________________________     
C
C     UPDATE OF FIELD VARIABLES
C 
C     STRESS TENSOR
C 
      STRESS=SS1
C    
C     TANGENT STIFFNESS OPERATOR 
C 
      DDSDDE=TANM
C
C     STRAIN ENERGY
C 
      SSE=SSE+DOT_PRODUCT((SS0+SS1)/2.0D0,DSTRAN)
C
C     SDV 1: CUMULATED PLASTIC STRAIN
C     SDV 2: SCALAR DAMAGAE VARIABLE
C     SDV 3-8: PLASTIC STRAIN VECTOR
C     SDV 9-14: NOMINAL STRESS VECTOR
C     SDV 15-20: DENSIFICATION STRESS VECTOR
C     SDV 21: ORIGINAL BVTV
C     SDV 22: UPDATED BVTV
C 
C     PLASTIC STRAIN TENSOR
      DO K1=3,8
        STATEV(K1)=EPLAS1(K1-2)
      END DO
C
C     CUMULATED PLASTIC STRAIN      
      STATEV(1)=KAPPA1
C     DAMAGE
      STATEV(2)=DAM(KAPPA1,KONSTD,CRITD)
C     BV/TV
      STATEV(21)=RHO
C 
      IF (DKAPPA1<0.0D0) THEN
        WRITE(*,*) 'Inadmissible DKappa occured'
        WRITE(*,*) 'Step : ',KSTEP
        WRITE(*,*) 'Inc : ',KINC
        WRITE(*,*) 'Elem : ',NOEL
        WRITE(*,*) 'Point : ',NPT
        WRITE(*,*) 'KAPPA1 : ',KAPPA1
        WRITE(*,*) 'DKAPPA1 : ',DKAPPA1
        WRITE(*,*) 'DAM(KAPPA) : ',STATEV(2)
      END IF
C 
      RETURN
      END
C     __________________________________________________________________
C
C     MATERIAL MODEL FUNCTIONS
C     __________________________________________________________________
C
C     TISSUE FUNCTION TSFU(RHO,EX,DELTA))
C 
      DOUBLE PRECISION FUNCTION TSFU(RHO,EX,DELTA)
      IMPLICIT NONE
      DOUBLE PRECISION RHO,EX,DELTA
      IF (RHO.LE.0.5D0) THEN
        TSFU=RHO**EX
      ELSE IF (RHO.GT.0.5D0) THEN
        TSFU=RHO**EX+(DELTA-1.0D0)*((RHO-0.5D0)/0.5D0)**EX
      ENDIF
      RETURN
      END
C
C     DAMAGE FUNCTION DAM(k)
C 
      DOUBLE PRECISION FUNCTION DAM(KAPPA,KONSTD,CRITD)
      IMPLICIT NONE
      DOUBLE PRECISION KAPPA,KONSTD,CRITD
C     MEAN KONSTK OF WOLFRAM (JBIOMECH 2011) FOR COMPRESSION AND 
C     TENSION, AXIAL AND TRANSVERSE: 8.0075, CRITD=0.85
      DAM=CRITD*(1.0D0-DEXP(-KONSTD*KAPPA))
      RETURN
      END
C
C     DERIVATIVE OF DAMAGE FUNCTION dDAM/dk
C 
      DOUBLE PRECISION FUNCTION DDAM(KAPPA,KONSTD,CRITD)
      IMPLICIT NONE
      DOUBLE PRECISION KAPPA,KONSTD,CRITD
C     MEAN KONSTK OF WOLFRAM (JBIOMECH 2011) FOR COMPRESSION AND 
C     TENSION, AXIAL AND TRANSVERSE: 8.0075, CRITD=0.85
      DDAM=CRITD*KONSTD*DEXP(-KONSTD*KAPPA)
      RETURN
      END
C
C     POSTYIELD FUNCTION r(k)
C 
      DOUBLE PRECISION FUNCTION RADK(PYFL,KSLOPE,KMAX,KWIDTH,RDY,
     1                                         KAPPA,KMIN,GMIN,ND,EXPS)
      IMPLICIT NONE
      DOUBLE PRECISION KSLOPE,KMAX,KWIDTH,RDY,KAPPA,OFFS
      DOUBLE PRECISION KMIN,GMIN,ND,EXPS
      INTEGER PYFL
C 
C     PERFECT PLASTICITY
      IF (PYFL.EQ.0) THEN
        RADK=1.0D0
C     EXPONENTIAL HARDENING
      ELSEIF (PYFL.EQ.1) THEN
        RADK=RDY+(1.0D0-RDY)*(1.0D0-DEXP(-KSLOPE*KAPPA))
C     SIMPLE SOFTENING FUNCTION
      ELSEIF (PYFL.EQ.2) THEN
        OFFS=1.0D0/KWIDTH 
        RADK=RDY+(1.0D0-RDY)*(DEXP(-((KAPPA-KMAX)**2)
     1                      /(KWIDTH*KMAX**2))-DEXP(-OFFS-KSLOPE*KAPPA))
C     CONTINUOUS SOFTENING FUNCTION WITH GMIN, KSLOPE=1000.0
      ELSEIF (PYFL.EQ.3) THEN
        OFFS=-DLOG(DEXP(-KMAX**2/(KMAX**2+0.1D0*KMIN**2))+GMIN*(1.0D0-
     1                         DEXP(-KMAX**2/(KMAX**2+0.1D0*KMIN**2))))
        KSLOPE=1000.0D0
        RADK=RDY+(1.0D0-RDY)*(DEXP(-((KAPPA-KMAX)**2)/(KMAX**2+0.1D0
     1          *KMIN**2))+GMIN*(1.0D0-DEXP(-((KAPPA-KMAX)**2)/(KMAX**2
     2                      +0.1D0*KMIN**2)))-DEXP(-OFFS-KSLOPE*KAPPA))
C     PIECEWISE SOFTENING FUNCTION
      ELSEIF (PYFL.EQ.4) THEN
C        WRITE(*,*) KMAX,KMIN,GMIN,ND,EXPS
        IF (KAPPA.LT.KMAX) THEN
          RADK=1.0D0-((KMAX-KAPPA)/KMAX)**(EXPS*KMAX)
        ELSEIF ((KAPPA.GE.KMAX).AND.(KAPPA.LT.(KMIN+KMAX)/2.0D0)) THEN
          RADK=1.0D0-((1.0D0-GMIN)/2.0D0)*((2.0D0*(KAPPA-KMAX))
     1             /(KMIN-KMAX))**ND
        ELSEIF ((KAPPA.GE.(KMIN+KMAX)/2.0D0).AND.(KAPPA.LT.KMIN)) THEN
          RADK=GMIN+((1.0D0-GMIN)/2.0D0)*((2.0D0*(KMIN-KAPPA))
     1             /(KMIN-KMAX))**ND
        ELSE 
          RADK=GMIN
        ENDIF
        RADK=RDY+(1.0D0-RDY)*RADK
      ENDIF
C
      RETURN
      END
C
C     DERIVATIVE OF POSTYIELD FUNCTION dr/dk
C 
      DOUBLE PRECISION FUNCTION DRADK(PYFL,KSLOPE,KMAX,KWIDTH,RDY,
     1                                         KAPPA,KMIN,GMIN,ND,EXPS)
      IMPLICIT NONE
      DOUBLE PRECISION KSLOPE,KMAX,KWIDTH,RDY,KAPPA,OFFS
      DOUBLE PRECISION KMIN,GMIN,ND,EXPS
      INTEGER PYFL
C
C     PERFECT PLASTICITY
      IF (PYFL.EQ.0) THEN
        DRADK=0.0D0
C     EXPONENTIAL HARDENING
      ELSEIF (PYFL.EQ.1) THEN
        DRADK=(1.0D0-RDY)*KSLOPE*DEXP(-KSLOPE*KAPPA)
C     SIMPLE SOFTENING FUNCTION WITH 
      ELSEIF (PYFL.EQ.2) THEN
        OFFS=1.0D0/KWIDTH 
        DRADK=(1.0D0-RDY)*((-KAPPA+KMAX)*DEXP(-(KAPPA-KMAX)**2
     1                        /(KWIDTH*KMAX**2))/(0.5D0*KWIDTH*KMAX**2)
     2                                 +KSLOPE*DEXP(-OFFS-KSLOPE*KAPPA))
C     CONTINUOUS SOFTENING FUNCTION WITH GMIN, KSLOPE=1000.0
      ELSEIF (PYFL.EQ.3) THEN
        OFFS=-DLOG(EXP(-KMAX**2/(KMAX**2+0.1D0*KMIN**2))+GMIN*(1.0D0-
     1                         DEXP(-KMAX**2/(KMAX**2+0.1D0*KMIN**2))))
        kslope=1000.0D0
        DRADK=(1.0D0-RDY)*(-2.0D0*(KAPPA-KMAX)/(KMAX**2+0.1D0*KMIN**2)
     1          *DEXP(-((KAPPA-KMAX)**2)/(KMAX**2+0.1D0*KMIN**2))+2.0D0
     2         *GMIN*(KAPPA-KMAX)/(KMAX**2+0.1D0*KMIN**2)*DEXP(-((KAPPA
     3            -KMAX)**2)/(KMAX**2+0.1D0*KMIN**2))+KSLOPE*DEXP(-OFFS
     4                                                  -KSLOPE*KAPPA))
C     PIECEWISE SOFTENING FUNCTION
      ELSEIF (PYFL.EQ.4) THEN
C        WRITE(*,*) KMAX,KMIN,GMIN,ND,EXPS
        IF (KAPPA.LT.KMAX) THEN
          DRADK=EXPS*((KMAX-KAPPA)/KMAX)**(EXPS*KMAX-1.0D0)
        ELSEIF ((KAPPA.GE.KMAX).AND.(KAPPA.LT.(KMIN+KMAX)/2.0D0))THEN
          DRADK=ND*(GMIN-1.0D0)/(KMIN-KMAX)*((2.0D0*(KAPPA-KMAX))
     1          /(KMIN-KMAX))**(ND-1.0D0)
        ELSEIF ((KAPPA.GE.(KMIN+KMAX)/2.0D0).AND.(KAPPA.LT.KMIN))THEN
          DRADK=ND*(1.0D0-GMIN)/(KMIN-KMAX)*((2.0D0*(KMIN-KAPPA))
     1          /(KMIN-KMAX))**(ND-1.0D0)
        ELSE 
          DRADK=0.0D0
        ENDIF
        DRADK=(1.0D0-RDY)*DRADK
      ENDIF
C 
      RETURN
      END
C
C     VISCOSITY FUNCTION
C
      DOUBLE PRECISION FUNCTION VISCY(VISCFL,ETA,MM,DTIME,DKAPPA,HI)
      IMPLICIT NONE
      DOUBLE PRECISION ETA,MM,DTIME,DKAPPA,HI
      INTEGER VISCFL
C     RATE-INDEPENDENT
      IF (VISCFL.EQ.0) THEN
        VISCY=0.0D0
C     LINEAR FLOW RULE
      ELSEIF (VISCFL.EQ.1) THEN
        VISCY=-ETA/DTIME*DKAPPA/HI
C     EXPONENTIAL FLOW RULE
      ELSEIF (VISCFL.EQ.2) THEN
        VISCY=-LOG(1.0D0+ETA/DTIME*DKAPPA/HI)/MM
C     LOGARITHMIC FLOW RULE
      ELSEIF (VISCFL.EQ.3) THEN
        VISCY=-(EXP(ETA/DTIME*DKAPPA/HI)-1.0D0)/MM
C     POLYNOMIAL FLOW RULE
      ELSEIF (VISCFL.EQ.4) THEN
        VISCY=0.5D0*MM-DSQRT((MM**2)/4.0D0+ETA/DTIME*DKAPPA/HI)
C     POWER LAW FLOW RULE
      ELSEIF (VISCFL.EQ.5) THEN
        VISCY=-SIGN(1.0D0,DKAPPA)*(ETA/DTIME
     1                                    *DABS(DKAPPA)/HI)**(1.0D0/MM)
      ENDIF
      RETURN
      END
C
      FUNCTION VDYDS(VISCFL,ETA,MM,DTIME,DKAPPA,DHDS,HI)
      IMPLICIT NONE
      DOUBLE PRECISION VDYDS(6)
      DOUBLE PRECISION ETA,MM,DTIME,DKAPPA,DHDS(6),HI
      INTEGER VISCFL
C     RATE-INDEPENDENT
      IF (VISCFL.EQ.0) THEN
        VDYDS=0.0D0
C     LINEAR FLOW RULE
      ELSEIF (VISCFL.EQ.1) THEN
        VDYDS=1.0D0/HI**2*DHDS*ETA/DTIME*DKAPPA
C     EXPONENTIAL FLOW RULE
      ELSEIF (VISCFL.EQ.2) THEN
        VDYDS=ETA/DTIME*DKAPPA/MM*DHDS/(HI**2)
     1                               *1.0D0/(1.0D0+ETA/DTIME*DKAPPA/HI)
C     LOGARITHMIC FLOW RULE
      ELSEIF (VISCFL.EQ.3) THEN
        VDYDS=ETA/DTIME*DKAPPA/MM*DHDS/(HI**2)*EXP(ETA/DTIME*DKAPPA/HI)
C     POLYNOMIAL FLOW RULE
      ELSEIF (VISCFL.EQ.4) THEN
        VDYDS=0.5D0*DHDS*ETA/DTIME*DABS(DKAPPA)/(HI**2)
     1                       /DSQRT((MM**2)/4.0D0+ETA/DTIME*DKAPPA/HI)
C     POWER LAW FLOW RULE
      ELSEIF (VISCFL.EQ.5) THEN
        VDYDS=1.0D0/MM/HI*DHDS*SIGN(1.0D0,DKAPPA)
     1                         *(ETA/DTIME*DABS(DKAPPA)/HI)**(1.0D0/MM)
      ENDIF
      RETURN
      END
C
      DOUBLE PRECISION FUNCTION VDYDK(VISCFL,ETA,MM,DTIME,DKAPPA,DHDK,
     1                                                              HI)
      IMPLICIT NONE
      DOUBLE PRECISION ETA,MM,DTIME,DKAPPA,DHDK,HI
      INTEGER VISCFL
C     RATE-INDEPENDENT
      IF (VISCFL.EQ.0) THEN
        VDYDK=0.0D0
C     LINEAR FLOW RULE
      ELSEIF (VISCFL.EQ.1) THEN
        VDYDK=-(HI-DKAPPA*DHDK)/HI**2*ETA/DTIME
C     EXPONENTIAL FLOW RULE
      ELSEIF (VISCFL.EQ.2) THEN
        VDYDK=-ETA/DTIME/MM*(HI-DKAPPA*DHDK)/HI**2
     3                               *1.0D0/(1.0D0+ETA/DTIME*DKAPPA/HI)
C     LOGARITHMIC FLOW RULE
      ELSEIF (VISCFL.EQ.3) THEN
        VDYDK=-ETA/DTIME/MM*(HI-DKAPPA*DHDK)/HI**2
     1                                        *EXP(ETA/DTIME*DKAPPA/HI)
C     POLYNOMIAL FLOW RULE
      ELSEIF (VISCFL.EQ.4) THEN
        VDYDK=-0.5D0*(HI-DKAPPA*DHDK)/HI**2*(ETA/DTIME)
     1                      /DSQRT((MM**2)/4.0D0+ETA/DTIME*DKAPPA/HI)
C     POWER LAW FLOW RULE
      ELSEIF (VISCFL.EQ.5) THEN
        VDYDK=-1.0D0/MM*SIGN(1.0D0,DKAPPA)*(SIGN(1.0D0,DKAPPA)*HI
     1               -DABS(DKAPPA)*DHDK)/HI**2*(ETA/DTIME)**(1.0D0/MM)
     2                              *(DABS(DKAPPA)/HI)**(1.0D0/MM-1.0)
      ENDIF
      RETURN
      END
C     __________________________________________________________________
C 
C     MATHEMATICAL FUNCTIONS
C     __________________________________________________________________
C     
C     INTRINSIC FUNCTIONS:
C
C     MATMUL(AAAA,BBBB)
C     MULTIPLICATION MATRIX WITH MATRIX
C
C     MATMUL(AAAA,BB)
C     MULTIPLICATION MATRIX WITH VECTOR
C
C     DOT_PRODUCT(AA,BB)
C     SCALAR PRODUCT OF TWO VECTORS
C 
C     EXTERNAL FUNCTIONS:
C     _________________________________________________________________
C 
      FUNCTION VECDYAD(BB,CC)
      IMPLICIT NONE
C     DYADIC PRODUCT AB OF VECTORS BB AND CC WITH DIMENSION 6x1  
      DOUBLE PRECISION BB(6),CC(6)
      DOUBLE PRECISION VECDYAD(6,6)
      INTEGER I,J
C 
      VECDYAD=0.0D0
C 
      VECDYAD=SPREAD(BB,2,SIZE(CC))*SPREAD(CC,1,SIZE(BB))
C 
      RETURN
      END
C     _________________________________________________________________
C 
      DOUBLE PRECISION FUNCTION VECNORM(DD)
      IMPLICIT NONE
C     NORM OF VECTOR AA WITH DIMENSION 6x1
      DOUBLE PRECISION DD(6)
C 
      VECNORM=DSQRT(DOT_PRODUCT(DD,DD))
C 
      RETURN
      END
C     __________________________________________________________________ 
C 
C     SUBROUTINES FOR MATRIX INVERSION
C     __________________________________________________________________
C 
      SUBROUTINE MIGS(A,N,X)
C
C     Subroutine to invert matrix A(N,N) with the inverse stored
C     in X(N,N) in the output. A is stored in STOA and is resituted
C     as outpout
C 
      IMPLICIT NONE
C 
      DOUBLE PRECISION A(N,N),STOA(N,N),B(N,N),X(N,N)
      INTEGER INDX(N),N,I,J,K
C 
      DO 140 I=1,N
        DO 130 J=1,N
          STOA(I,J)=A(I,J)
          B(I,J)=0.0D0
  130   CONTINUE
  140 CONTINUE
      DO 150 I=1,N
        B(I,I)=1.0D0
  150 CONTINUE
C 
      CALL ELGS(A,N,INDX)
C 
      DO 180 I=1,N-1
        DO 170 J=I+1,N
          DO 160 K=1,N
            B(INDX(J),K)=B(INDX(J),K)
     1                    -A(INDX(J),I)*B(INDX(I),K)
  160     CONTINUE
  170   CONTINUE
  180 CONTINUE
C 
      DO 210 I=1,N
        X(N,I)=B(INDX(N),I)/A(INDX(N),N)
        DO 200 J=N-1,1,-1
          X(J,I)=B(INDX(J),I)
          DO 190 K=J+1,N
            X(J,I)=X(J,I)-A(INDX(J),K)*X(K,I)
  190     CONTINUE
          X(J,I)= X(J,I)/A(INDX(J),J)
  200   CONTINUE
  210 CONTINUE
C
C Restitution of A
C 
      DO 230 I=1,N
        DO 220 J=1,N
          A(I,J)=STOA(I,J)
  220   CONTINUE
  230 CONTINUE
C 
      RETURN
      END
C     __________________________________________________________________
C 
      SUBROUTINE ELGS(A,N,INDX)
C
C     Subroutine to perform the partial-pivoting Gaussian elimination.
C     A(N,N) is the original matrix in the input and transformed
C     matrix plus the pivoting element ratios below the diagonal in
C     the output.  INDX(N) records the pivoting order.
C 
      IMPLICIT NONE
C 
      DOUBLE PRECISION A(N,N),C(N)
      INTEGER N, INDX(N)
      DOUBLE PRECISION C1,PI1,PI,PJ
      INTEGER K,ITMP,I,J
C
C     Initialize the index
C 
      DO 240 I=1,N
        INDX(I)=I
  240 CONTINUE
C
C     Find the rescaling factors, one from each row
C 
        DO 260 I=1,N
          C1= 0.0
          DO 250 J=1,N
            C1=DMAX1(C1,DABS(A(I,J)))
  250     CONTINUE
          C(I)=C1
  260   CONTINUE
C
C     Search the pivoting (largest) element from each column
C 
      DO 300 J=1,N-1
        PI1=0.0
        DO 270 I=J,N
          PI=DABS(A(INDX(I),J))/C(INDX(I))
          IF (PI.GT.PI1) THEN
            PI1=PI
            K=I
          ELSE
          END IF
  270   CONTINUE
C
C     Interchange the rows via INDX(N) to record pivoting order
C 
        ITMP=INDX(J)
        INDX(J)=INDX(K)
        INDX(K)=ITMP
        DO 290 I=J+1,N
          PJ=A(INDX(I),J)/A(INDX(J),J)
C
C     Record pivoting ratios below the diagonal
C 
          A(INDX(I),J)=PJ
C
C     Modify other elements accordingly
C 
          DO 280 K=J+1,N
            A(INDX(I),K)=A(INDX(I),K)-PJ*A(INDX(J),K)
  280     CONTINUE
  290   CONTINUE
  300 CONTINUE
C 
      RETURN
      END
C     __________________________________________________________________
C
      character*(*) FUNCTION dmkname(fname,dname,exten)
C     COMPOSE A FILENAME AS directory/jobname.exten
C
      character*(*) fname,dname,exten
C     fname  I   jobname
C     dname  I   directory
C     exten  I   extension
C     dmkname O directory/jobname.exten

      ltot = len(fname)
      lf = 0
      DO k1 = ltot,2,-1
        if (lf.EQ.0.AND.fname(k1:k1).NE.' ')  lf = k1
      END DO

      ltot = len(dname)
      ld = 0
      DO k1 = ltot,2,-1
        IF (ld.EQ.0.AND.dname(k1:k1).NE.' ')  ld = k1
      END DO

      ltot = len(exten)
      le = 0
      DO k1 = ltot,2,-1
        IF (le.EQ.0.AND.exten(k1:k1).NE.' ')  le = k1
      END DO

      IF ((lf + ld + le) .LE. len(dmkname)) THEN
        dmkname = dname(1:ld)//'/'//fname(1:lf)
        ltot = ld + lf + 1
        IF ( le.GT.0) THEN
           dmkname = dmkname(1:ltot)//exten(1:le)
        END IF
      END IF
C
      RETURN
      END
C

